# Generated by Django 5.2.14 on 2026-08-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdoc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_four',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_four_item_one_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_four_item_two_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_one',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_one_item_one_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_one_item_two_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_three',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_three_item_one_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_three_item_two_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_two',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_two_item_one_value',
        ),
        migrations.RemoveField(
            model_name='comparisontable',
            name='criteria_two_item_two_value',
        ),
        migrations.CreateModel(
            name='ComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=100)),
                ('item_one_value', models.TextField(blank=True)),
                ('item_two_value', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='researchdoc.comparisontable')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
